
name: Add issues to project board
description: Add issues to github projects boards

inputs:
  github-token:
    description: 'Github token'
    required: true
  organizations:
    description: Comma separated list of Github organizations where to search issues in
    required: true
  issues-labels: 
    description: Comma separated list of labels of the issues to be searched
    required: true
  time-interval: 
    description: Time range filter for issues
    required: true
  project-number:
    description: Number of the project board where issues must be added
    required: true 
  column-name:
    description: Name of the project board column where issues must be added
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'plus'
  color: 'green'