
name: 'Add Good First Issues to Bench'

description: 'Adds good first issues to the bench board'

branding:
  icon: "check-square"
  color: "green"

inputs:
  github-token:
    description: Your Github token, it's already available to your Github action.
    required: true
  organization::
    description: The GitHub organization where issues are pulled from.
    required: true
  time-interval:
    description: The timeframe during which issues to be found were last updated. Example: "1 day" to pull issues updated over the past day (24hrs).
    required: true
    default: "1 day"

runs:
    using: 'composite'
    steps:
      - name: Checkout the fresh project
        uses: actions/checkout@v2

      - name: Add issues to bench board
        uses: actions/github-script@v1
        with:
          github-token: ${{ inputs.github-token }}
          organization: ${{ inputs.organization }}
          time-interval: ${{ inputs.time-interval }}
          script: |
            const script = require('${{ github.action_path }}/dist/index.js')
            await script({ github, context, inputs: ${{ toJSON(inputs) }} })
