name: Add issues to project

on:
  workflow_dispatch:
    inputs:
      organizations:
        description: 'organizations for issues'
        required: true
      issues-labels: 
        description: 'issues labels'
        required: false
        default: 'good first issues'
      time-interval:
        description: 'time range filter'
        required: true
      project-number:
        description: 'project board number'
        required: true
      column-name: 
        description: 'project board column name'
        required: false
        default: 'to do'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Add issues to board
        uses: nearform/github-action-add-issues-to-project@master
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          organizations: ${{ github.event.inputs.organizations }}
          issues-labels: ${{ github.event.inputs.issues-labels }}
          time-interval: ${{ github.event.inputs.time-interval }}
          project-number: ${{ github.event.inputs.project-number }}
          column-name: ${{ github.event.inputs.column-name }}

