name: good-first-issues
on:
  workflow_dispatch:
    inputs:
      organizations:
        description: 'organizations for issues'
        required: true
        default: 'fastify'
      time-interval:
        description: 'time range filter'
        required: true
        default: '10 days'
      project-id:
        description: 'project id'
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PROJECTS_PAT }}
          repository: nearform/github-action-bench-good-first-issues
          ref: master
          path: good-first-issues
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PROJECTS_PAT }}
          script: |
            const script = require('./good-first-issues/dist/index.js')
            await script({ context, token: "${{ secrets.GH_PROJECTS_PAT }}", inputs: ${{ toJSON(github.event.inputs) }} })
